[package]
name = "apexscan-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "apexscan"
path = "src/main.rs"

[dependencies]
apexscan-core = { path = "../apexscan-core" }
apexscan-packet = { path = "../apexscan-packet" }
apexscan-scanner = { path = "../apexscan-scanner" }
apexscan-discovery = { path = "../apexscan-discovery" }
apexscan-fingerprint = { path = "../apexscan-fingerprint" }
apexscan-scripting = { path = "../apexscan-scripting" }
apexscan-timing = { path = "../apexscan-timing" }

tokio = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
