[package]
name = "apexscan-packet"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
apexscan-core = { path = "../apexscan-core" }

pnet = { workspace = true }
pnet_packet = { workspace = true }
socket2 = { workspace = true }
tokio = { workspace = true }
libc = { workspace = true }

thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
