[package]
name = "apexscan-discovery"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
apexscan-core = { path = "../apexscan-core" }
apexscan-packet = { path = "../apexscan-packet" }

tokio = { workspace = true }
tracing = { workspace = true }
